
services:
  app:
    container_name: delayedNotifier
    build:
      context: .
      dockerfile: Dockerfile
    image: service
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      .env
    depends_on:
      pg-local:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
    restart: always

  web:
    container_name: commentTree-web
    build:
      context: ./web
      dockerfile: Dockerfile
    command: npm run dev:vite
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.13-management  # Specify a more precise version
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  migrate:
    image: migrate/migrate:v4.15.2
    container_name: migration
    depends_on:
      - pg-local
      - app
    command: [
      "-path=/app/migrations", # <---  Путь внутри контейнера
      "-database=postgres://postgres:1@pg-local:5432/postgres?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/app/migrations  # <---  Изменен локальный путь
    networks:
      - app-network

  redis:
    container_name: redis
    image: docker.io/bitnami/redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - app-network

  pg-local:
    container_name: pg-local
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg-local-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg-local-data: